# Generated by Django 3.2.13 on 2022-05-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='book_marked_as_read',
            field=models.BooleanField(default=False),
        ),
    ]
