# Generated by Django 3.2.13 on 2022-05-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_wishlistitem_book_marked_as_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
