# Generated by Django 3.2.13 on 2022-05-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_alter_review_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='purchase_link',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='review',
            name='slug',
            field=models.SlugField(editable=False, max_length=240, unique=True),
        ),
    ]
