# Generated by Django 3.2.13 on 2022-05-11 15:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20220510_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='book_cover',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dpsodnurd/image/upload/v1652144706/pylwugl05ovxnbmaa8rs.jpg', max_length=255, verbose_name='image'),
        ),
    ]
