# Generated by Django 3.2.13 on 2022-05-12 01:25

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_alter_review_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='star_rating2',
            field=models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='book_cover',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dpsodnurd/image/upload/v1652284886/m6mvsjkb3eqpn2wczqsu.jpg', max_length=255, verbose_name='image'),
        ),
    ]
