# Generated by Django 3.2.13 on 2022-05-14 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_auto_20220514_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='reviews.category', verbose_name='Book Category'),
        ),
        migrations.AlterField(
            model_name='review',
            name='purchase_link',
            field=models.URLField(blank=True, max_length=400, verbose_name='Purchase Link URL'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Book Title'),
        ),
    ]
