# Generated by Django 3.2.13 on 2022-05-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_auto_20220514_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='book_author',
            field=models.CharField(max_length=200, verbose_name='Book Author'),
        ),
    ]
